### ISSUE TITLE
  Cannot read property 'rate' of null

### ISSUE THREAD

**Issue by adamwilbert** [ajmath/serverless-offline-scheduler#25]
Followed installation example, added scheduled event to one function in sls yml, cannot start offline or run sls schedule without getting   `Cannot read property 'rate' of null` error

**Comment by ajmath** [comment]
Can you provide an example serverless.yml file?

**Comment by adamwilbert** [comment]
```
    events:
      - schedule:
          name: ${self:service}-${self:provider.stage}-func-warmer
          rate: rate(5 minutes)
          enabled: true
          input:
            warmer: true
            concurrency: 1
```
