### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by Meemaw** [ajmath/serverless-offline-scheduler#30]
I'm trying out this plugin via:
```sh
λ → sls schedule
Serverless: scheduler: scheduling schedule-executors/schedule-executors with */1 * * * *
Serverless: schedule-executors
```
and
```sh
λ → serverless offline
```

... but I'm not seeing anything happening.

Functionn is defined as:
```yml
functions:
  schedule-executors:
    handler: src/functions/scheduleExecutors/index.handler
    events:
      - schedule:
          name: your-scheduled-rate-event-name
          description: 'your scheduled rate event description'
          rate: rate(1 minute)  
```
